name: metanorma
base: core20
version: '1.12.7'
summary: Metanorma documentation generator
description: "Metanorma an open-source framework for writing and publishing standards documents with a focus on semantic authoring and flexible output support. Here's what you can do with Metanorma: \n- Build tools for authoring standards and formatting them in accordance with your organization's practices\n- Use the existing processor ecosystem to create documents compliant to the requirements of ISO, RFC, CalConnect, and others.\n"
grade: stable
confinement: strict
architectures:
  - build-on: amd64
apps:
  metanorma:
    command: bin/metanorma
    environment:
      PATH: $SNAP/local/bin:$SNAP/usr/lib/jvm/java-17-openjdk-amd64/bin:$PATH
      DEBUG: "*:*"
      GIT_EXEC_PATH: $SNAP/usr/lib/git-core # https://forum.snapcraft.io/t/using-git-from-a-program/12599/11?u=camobap
      GIT_CONFIG_NOSYSTEM: 'true' # https://github.com/metanorma/metanorma-snap/issues/12
      XDG_DATA_HOME: $SNAP/usr/share # NPE in sun.awt.FontConfiguration.getVersion, https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1576303
    plugs:
      - browser-support
      - network
      - gsettings
      - home
  plantuml:
    command: usr/lib/jvm/java-17-openjdk-amd64/bin/java -jar $SNAP/jar/plantuml-1.2022.12.jar
parts:
  packed-mn:
    plugin: dump
    source: https://github.com/metanorma/packed-mn/releases/download/v$SNAPCRAFT_PROJECT_VERSION/metanorma-linux-x86_64.tgz
    organize:
      metanorma-linux-x86_64: bin/metanorma
    stage-packages:
      - git-core
      - zlib1g
      - libgcrypt20
      - liblzma5
      - libdb5.3
      - libselinux1
      - libsystemd0
      - libtinfo5
      - libudev1
      - libmspack-dev
  plantuml:
    plugin: nil
    override-build: |
      mkdir $SNAPCRAFT_PART_INSTALL/jar
      wget --quiet https://github.com/plantuml/plantuml/releases/download/v1.2022.12/plantuml-1.2022.12.jar -O $SNAPCRAFT_PART_INSTALL/jar/plantuml-1.2022.12.jar
    build-packages:
      - wget
      # https://askubuntu.com/questions/1054854/snap-package-error-uploading
      - ca-certificates
      - ca-certificates-java
      - openjdk-17-jre-headless
    stage-packages:
      - libgcrypt20
      - liblzma5
      - libselinux1
      - libsystemd0
      - zlib1g
      - graphviz
      - openjdk-17-jre-headless
  xml2rfc:
    plugin: python
    python-packages: [idnits, xml2rfc]
    stage-packages:
      - libbz2-1.0
      - libtinfo5
      - zlib1g
      - libdb5.3
      - libncursesw5
